site_name: Stacker Build
site_url: https://stackerbuild.io
site_description: Stacker Build Docuementation
repo_url: https://github.com/project-stacker/stacker
repo_name: project-stacker/stacker
edit_uri: ""
copyright: Copyright &copy; 2017 - 2022 Cisco Systems Inc., All Rights Reserved.
theme:
  name: material
  custom_dir: material
  palette:
    - scheme: slate
      toggle:
        name: Light Mode
        icon: material/toggle-switch-off-outline
      primary: black
      accent: lime
      media: "(prefers-color-scheme: dark)"
    - scheme: default
      toggle:
        name: Dark Mode
        icon: material/toggle-switch
      primary: black
      accent: teal
      media: "(prefers-color-scheme: light)"
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono
extra:
  homepage: https://stackerbuild.io
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/project-stacker/stacker.git
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/stackerbuild
plugins:
  - search
  - minify:
      minify_html: true
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Get Started:
    - Get Stacker: get_started/get_stacker.md
    - Build Image: get_started/build_image.md
  - Concepts:
    - OCI Image Layout: concepts/oci_image_layout.md
    - Stacker Architecture: concepts/stacker_architecture.md
    - Multi-Layer Build: concepts/multi_layer_build.md
    - Incremental Build: concepts/incremental_build.md
    - SquashFS Layer: concepts/squashfs_layer.md
  - User Guide:
    - Runtime Environment: user_guide/runtime_environment.md
    - Image Build: user_guide/image_build.md
    - Templates: user_guide/templates.md
    - Annotation Support: user_guide/annotation_support.md
    - Scratch Image: user_guide/scratch_image.md
    - Dependency Builds: user_guide/dependency_builds.md
    - Publish Images: user_guide/publish_images.md
    - Build Cache: user_guide/build_cache.md
    - Inspect Images: user_guide/inspect_images.md
    - Image Chroot: user_guide/image_chroot.md
    - Grab Image Content: user_guide/grab_image_content.md
    - SquashFS Images: user_guide/squashfs_images.md
    - Debugging: user_guide/debugging.md
  - Reference:
    - Stacker CLI: reference/stacker_cli.md
    - Stacker File: reference/stacker_file.md
  - Developer Guide:
    - Building Stacker: developer_guide/building_stacker.md
    - Code Structure: developer_guide/code_structure.md
    - LXC Usage: developer_guide/lxc_usage.md
    - OverlayFS Usage: developer_guide/overlayfs_usage.md
  - License: license.md
